In [1]:
import pyterrier as pt
from pathlib import Path
from pyterrier.measures import RR, nDCG, MAP
from fast_forward.encoder import TASBEncoder
import torch
from fast_forward.util import Indexer
from fast_forward.util.pyterrier import FFScore
from fast_forward.util.pyterrier import FFInterpolate
print(pt.__version__)

C:\Users\lazar\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

0.12.1

Our experiment consists of four phases:
1) We only evaluate BM25 performance on the datasets (evSciFact, FiQA, TREC-COVID, NFCorpus)
2) We retrieve top-k (test several k values) and then use the pretrained neural reranker and evaluate the scores. Since the neural reranker is trained on MSMACRO we can't use it for evaluation.
3) We now check out the hybrid pipeline (interpolate BM25 with neural reranker) , so here we also test several k values and some α values
4) We need to test if the α value works across datasets (fix k value - found a good one in previous step) and tune α on one dataset (e.g Fiqa) and test it on the others.

## Create sparse indexes for BM25 for all datasets
We measure the performance of BM25 on our datasets

In [2]:
# first we import all our datasets:
# finance domain with some technical language usually for QA retrieval
fiqa = pt.get_dataset("irds:beir/fiqa")

# this dataset has structured and formal language (domain:science) and used for evidence retrieval
scifact = pt.get_dataset("irds:beir/scifact")

# arguana is a semantic dataset in the domain of debates/argumentation
arguana = pt.get_dataset("irds:beir/arguana")

# general QA dataset
nfcorpus = pt.get_dataset("irds:beir/nfcorpus")

In [3]:

fiqa_indexer = pt.IterDictIndexer(
    str(Path.cwd()),  # this will be ignored
    type=pt.index.IndexingType.MEMORY,
)
fiqa_index_ref = fiqa_indexer.index(fiqa.get_corpus_iter(), fields=["text"])

Java started (triggered by TerrierIndexer.__init__) and loaded: pyterrier.java, pyterrier.terrier.java [version=5.11 (build: craig.macdonald 2025-01-13 21:29), helper_version=0.0.8]
beir/fiqa documents: 100%|█████████████████████████████████████████████████████| 57638/57638 [00:18<00:00, 3039.70it/s]

In [4]:
# index for scifact
scifact_indexer = pt.IterDictIndexer(
    str(Path.cwd()),  # this will be ignored
    type=pt.index.IndexingType.MEMORY,
)
scifact_index_ref = scifact_indexer.index(scifact.get_corpus_iter(), fields=["text"])

beir/scifact documents: 100%|████████████████████████████████████████████████████| 5183/5183 [00:02<00:00, 1963.63it/s]

In [5]:
# index for nfcorpus
nfcorpus_indexer = pt.IterDictIndexer(
    str(Path.cwd()),  # this will be ignored
    type=pt.index.IndexingType.MEMORY,
)
nfcorpus_index_ref = nfcorpus_indexer.index(nfcorpus.get_corpus_iter(),fields=["text"])

beir/nfcorpus documents: 100%|███████████████████████████████████████████████████| 3633/3633 [00:01<00:00, 2220.05it/s]

In [6]:
# index for arguana
arguana_indexer = pt.IterDictIndexer(
    str(Path.cwd()),  # this will be ignored
    type=pt.index.IndexingType.MEMORY,
    meta={"docno": 100} # it has large ids
)
arguana_index_ref = arguana_indexer.index(arguana.get_corpus_iter(),fields=["text"])

beir/arguana documents: 100%|████████████████████████████████████████████████████| 8674/8674 [00:03<00:00, 2736.56it/s]

## Phase 1 - evaluate only with BM25

In [7]:
# Phase 1 - evaluate retrieval only with BM25
# fiqa dataset
bm25_fiqa = pt.terrier.Retriever(fiqa_index_ref, wmodel="BM25")
testset_fiqa = pt.get_dataset("irds:beir/fiqa/test")
pt.Experiment(
    [bm25_fiqa],
    testset_fiqa.get_topics(),
    testset_fiqa.get_qrels(),
    eval_metrics=[RR @ 10, nDCG @ 10, MAP @ 100],
)

10:27:34.877 [main] WARN org.terrier.querying.ApplyTermPipeline -- The index has no termpipelines configuration, and no control configuration is found. Defaulting to global termpipelines configuration of 'Stopwords,PorterStemmer'. Set a termpipelines control to remove this warning.

                name     RR@10   nDCG@10   AP@100
0  TerrierRetr(BM25)  0.310271  0.252589  0.20864

In [8]:
# scifact dataset
bm25_scifact = pt.terrier.Retriever(scifact_index_ref, wmodel="BM25")
testset_scifact = pt.get_dataset("irds:beir/scifact/test")
pt.Experiment(
    [bm25_scifact],
    testset_scifact.get_topics(),
    testset_scifact.get_qrels(),
    eval_metrics=[RR @ 10, nDCG @ 10, MAP @ 100],
)

10:27:48.775 [main] WARN org.terrier.querying.ApplyTermPipeline -- The index has no termpipelines configuration, and no control configuration is found. Defaulting to global termpipelines configuration of 'Stopwords,PorterStemmer'. Set a termpipelines control to remove this warning.

                name     RR@10   nDCG@10    AP@100
0  TerrierRetr(BM25)  0.632427  0.672167  0.626749

In [9]:
# arguana dataset
bm25_arguana = pt.terrier.Retriever(arguana_index_ref, wmodel="BM25")
testset_arguana = pt.get_dataset("irds:beir/arguana")
pt.Experiment(
    [bm25_arguana],
    testset_arguana.get_topics(),
    testset_arguana.get_qrels(),
    eval_metrics=[RR @ 10, nDCG @ 10, MAP @ 100],
)

10:27:54.756 [main] WARN org.terrier.querying.ApplyTermPipeline -- The index has no termpipelines configuration, and no control configuration is found. Defaulting to global termpipelines configuration of 'Stopwords,PorterStemmer'. Set a termpipelines control to remove this warning.

                name     RR@10   nDCG@10    AP@100
0  TerrierRetr(BM25)  0.225617  0.342442  0.236988

In [10]:
# nfcorpus dataset
bm25_nfcorpus = pt.terrier.Retriever(nfcorpus_index_ref, wmodel="BM25")
testset_nfcorpus = pt.get_dataset("irds:beir/nfcorpus/test")
pt.Experiment(
    [bm25_nfcorpus],
    testset_nfcorpus.get_topics("text"),
    testset_nfcorpus.get_qrels(),
    eval_metrics=[RR @ 10, nDCG @ 10, MAP @ 100],
)

10:28:26.434 [main] WARN org.terrier.querying.ApplyTermPipeline -- The index has no termpipelines configuration, and no control configuration is found. Defaulting to global termpipelines configuration of 'Stopwords,PorterStemmer'. Set a termpipelines control to remove this warning.

                name     RR@10   nDCG@10    AP@100
0  TerrierRetr(BM25)  0.534378  0.322219  0.143582

## Phase 2 - Neural reranker

We are going to use a pretrained neural model to rerank the top-k candidates. We are going to test several candidate depths to see how the performance reacts. I will test various candidate depths here but not on all the datasets, probably 2 of them are enough to make the assumptions neccessary

In [11]:
q_encoder = d_encoder = TASBEncoder(
    device="cuda:0" if torch.cuda.is_available() else "cpu"
)

In [28]:
from fast_forward.index import OnDiskIndex, Mode
# create the empty dense indexes on disk

def create_index_onDisk(data_name):
    index_name = "ffindex_" + data_name + "_tasb.h5" 
    
    ff_index_path  = Path.cwd() / "ir_experiments" / index_name
    ff_index_path.parent.mkdir(exist_ok=True, parents=True)
    
    try:
        ff_index = OnDiskIndex(
            ff_index_path,
            query_encoder=q_encoder,
            mode=Mode.MAXP,
            max_id_length=64
        )
        return ff_index
    except Exception as e:
        return  OnDiskIndex.load(ff_index_path)
    
scifact_index=create_index_onDisk("scifact")
fiqa_index=create_index_onDisk("fiqa")
arguana_index=create_index_onDisk("arguana")
nfcorpus_index=create_index_onDisk("nfcorpus")

100%|██████████████████████████████████████████████████████████████████████████| 5183/5183 [00:00<00:00, 700876.22it/s]
100%|███████████████████████████████████████████████████████████████████████| 57638/57638 [00:00<00:00, 1686829.15it/s]
100%|█████████████████████████████████████████████████████████████████████████| 8674/8674 [00:00<00:00, 1776348.46it/s]

In [13]:
def docs_iter(dataset):
    for d in dataset.get_corpus_iter():
        yield {"doc_id": d["docno"], "text": d["text"]}

## **ONLY RUN THE FOLLOWING THREE LINES IF WE HAVE MADE A MISTAKE IN THE IMPLEMENTATION**

In [ ]:
#fill in scifact dense index  !!!!!! DON'T RUN THIS I HAVE CREATED THIS ALREADY !!!!!!!!!
Indexer(scifact_index, d_encoder, batch_size=8).from_dicts(docs_iter(scifact))

In [ ]:
#fill in fiqa dense index !!!!!! DON'T RUN THIS I HAVE CREATED THIS ALREADY !!!!!!!!!
Indexer(fiqa_index, d_encoder, batch_size=8).from_dicts(docs_iter(fiqa))

In [14]:
#fill in arguana dense index !!!!!! DON'T RUN THIS I HAVE CREATED THIS ALREADY !!!!!!!!!
Indexer(arguana_index, d_encoder, batch_size=8).from_dicts(docs_iter(arguana))

0it [00:00, ?it/s]
8it [00:01,  4.51it/s]:   0%|                                                                 | 0/8674 [00:00<?, ?it/s]
16it [00:02,  7.19it/s]   0%|                                                         | 8/8674 [00:01<31:58,  4.52it/s]
24it [00:02,  9.83it/s]   0%|                                                        | 16/8674 [00:02<20:03,  7.19it/s]
32it [00:03, 12.86it/s]   0%|▏                                                       | 24/8674 [00:02<14:39,  9.84it/s]
40it [00:03, 13.73it/s]   0%|▏                                                       | 32/8674 [00:03<11:11, 12.86it/s]
48it [00:04, 13.00it/s]   0%|▎                                                       | 40/8674 [00:03<10:28, 13.74it/s]
56it [00:05,  9.41it/s]   1%|▎                                                       | 48/8674 [00:04<11:03, 13.00it/s]
64it [00:06,  9.91it/s]   1%|▎                                                       | 56/8674 [00:05<15:15,  9.41it/s]
72it [00:07, 10.12it/s]   1%|▍                                                       | 64/8674 [00:06<14:28,  9.91it/s]
80it [00:07, 10.48it/s]   1%|▍                                                       | 72/8674 [00:07<14:10, 10.12it/s]
88it [00:08, 10.72it/s]   1%|▌                                                       | 80/8674 [00:07<13:40, 10.48it/s]
96it [00:09, 10.49it/s]   1%|▌                                                       | 88/8674 [00:08<13:20, 10.72it/s]
104it [00:10,  9.34it/s]  1%|▌                                                       | 96/8674 [00:09<13:37, 10.49it/s]
112it [00:11, 10.54it/s]  1%|▋                                                      | 104/8674 [00:10<15:17,  9.34it/s]
120it [00:11, 11.66it/s]  1%|▋                                                      | 112/8674 [00:11<13:32, 10.54it/s]
128it [00:12, 11.94it/s]  1%|▊                                                      | 120/8674 [00:11<12:13, 11.66it/s]
136it [00:13, 10.61it/s]  1%|▊                                                      | 128/8674 [00:12<11:55, 11.94it/s]
144it [00:13, 11.64it/s]  2%|▊                                                      | 136/8674 [00:13<13:24, 10.61it/s]
152it [00:14, 12.83it/s]  2%|▉                                                      | 144/8674 [00:13<12:12, 11.64it/s]
160it [00:14, 12.12it/s]  2%|▉                                                      | 152/8674 [00:14<11:04, 12.83it/s]
168it [00:15, 12.97it/s]  2%|█                                                      | 160/8674 [00:14<11:42, 12.12it/s]
176it [00:16,  9.14it/s]  2%|█                                                      | 168/8674 [00:15<10:55, 12.97it/s]
184it [00:17,  8.55it/s]  2%|█                                                      | 176/8674 [00:16<15:29,  9.15it/s]
192it [00:18,  8.94it/s]  2%|█▏                                                     | 184/8674 [00:17<16:33,  8.55it/s]
200it [00:19, 10.21it/s]  2%|█▏                                                     | 192/8674 [00:18<15:49,  8.94it/s]
208it [00:20,  8.20it/s]  2%|█▎                                                     | 200/8674 [00:19<13:49, 10.21it/s]
216it [00:22,  7.07it/s]  2%|█▎                                                     | 208/8674 [00:20<17:12,  8.20it/s]
224it [00:23,  6.79it/s]  2%|█▎                                                     | 216/8674 [00:22<19:55,  7.07it/s]
232it [00:24,  7.42it/s]  3%|█▍                                                     | 224/8674 [00:23<20:44,  6.79it/s]
240it [00:25,  7.62it/s]  3%|█▍                                                     | 232/8674 [00:24<18:57,  7.42it/s]
248it [00:26,  6.98it/s]  3%|█▌                                                     | 240/8674 [00:25<18:27,  7.62it/s]
256it [00:27,  8.48it/s]  3%|█▌                                                     | 248/8674 [00:26<20:06,  6.98it/s]
264it [00:28,  8.23it/s]  3%|█▌                                                     | 256/8674 [00:27<16:32,  8.48it/s]
272it [00:29,  8.30it/s]  3%|█▋                                                     | 264/8674 [00:28<17:02,  8.23it/s]
280it [00:29,  8.56it/s]  3%|█▋                                                     | 272/8674 [00:29<16:51,  8.30it/s]
288it [00:30,  8.99it/s]  3%|█▊                                                     | 280/8674 [00:29<16:20,  8.56it/s]
296it [00:32,  7.43it/s]  3%|█▊                                                     | 288/8674 [00:30<15:32,  8.99it/s]
304it [00:33,  6.68it/s]  3%|█▉                                                     | 296/8674 [00:32<18:47,  7.43it/s]
312it [00:34,  7.39it/s]  4%|█▉                                                     | 304/8674 [00:33<20:52,  6.68it/s]
320it [00:36,  6.76it/s]  4%|█▉                                                     | 312/8674 [00:34<18:51,  7.39it/s]
328it [00:37,  6.73it/s]  4%|██                                                     | 320/8674 [00:35<20:35,  6.76it/s]
336it [00:38,  7.42it/s]  4%|██                                                     | 328/8674 [00:37<20:40,  6.73it/s]
344it [00:38,  8.79it/s]  4%|██▏                                                    | 336/8674 [00:38<18:43,  7.42it/s]
352it [00:39,  8.74it/s]  4%|██▏                                                    | 344/8674 [00:38<15:47,  8.79it/s]
360it [00:40,  7.39it/s]  4%|██▏                                                    | 352/8674 [00:39<15:51,  8.74it/s]
368it [00:42,  6.64it/s]  4%|██▎                                                    | 360/8674 [00:40<18:45,  7.39it/s]
376it [00:43,  6.16it/s]  4%|██▎                                                    | 368/8674 [00:42<20:50,  6.64it/s]
384it [00:44,  6.91it/s]  4%|██▍                                                    | 376/8674 [00:43<22:26,  6.16it/s]
392it [00:46,  6.37it/s]  4%|██▍                                                    | 384/8674 [00:44<19:59,  6.91it/s]
400it [00:47,  7.13it/s]  5%|██▍                                                    | 392/8674 [00:46<21:39,  6.37it/s]
408it [00:48,  6.52it/s]  5%|██▌                                                    | 400/8674 [00:47<19:20,  7.13it/s]
416it [00:49,  7.01it/s]  5%|██▌                                                    | 408/8674 [00:48<21:08,  6.52it/s]
424it [00:50,  7.15it/s]  5%|██▋                                                    | 416/8674 [00:49<19:38,  7.01it/s]
432it [00:51,  7.68it/s]  5%|██▋                                                    | 424/8674 [00:50<19:13,  7.15it/s]
440it [00:52,  7.67it/s]  5%|██▋                                                    | 432/8674 [00:51<17:52,  7.68it/s]
448it [00:52,  9.32it/s]  5%|██▊                                                    | 440/8674 [00:52<17:53,  7.67it/s]
456it [00:53,  8.71it/s]  5%|██▊                                                    | 448/8674 [00:52<14:42,  9.32it/s]
464it [00:55,  8.31it/s]  5%|██▉                                                    | 456/8674 [00:53<15:43,  8.71it/s]
472it [00:56,  8.23it/s]  5%|██▉                                                    | 464/8674 [00:55<16:28,  8.31it/s]
480it [00:56,  8.90it/s]  5%|██▉                                                    | 472/8674 [00:56<16:36,  8.23it/s]
488it [00:57, 10.38it/s]  6%|███                                                    | 480/8674 [00:56<15:20,  8.90it/s]
496it [00:57, 11.50it/s]  6%|███                                                    | 488/8674 [00:57<13:08, 10.38it/s]
504it [00:58,  9.54it/s]  6%|███▏                                                   | 496/8674 [00:57<11:51, 11.50it/s]
512it [01:00,  7.74it/s]  6%|███▏                                                   | 504/8674 [00:58<14:16,  9.54it/s]
520it [01:01,  7.31it/s]  6%|███▏                                                   | 512/8674 [01:00<17:34,  7.74it/s]
528it [01:02,  6.86it/s]  6%|███▎                                                   | 520/8674 [01:01<18:35,  7.31it/s]
536it [01:03,  7.37it/s]  6%|███▎                                                   | 528/8674 [01:02<19:47,  6.86it/s]
544it [01:04,  8.51it/s]  6%|███▍                                                   | 536/8674 [01:03<18:23,  7.37it/s]
552it [01:05,  9.43it/s]  6%|███▍                                                   | 544/8674 [01:04<15:55,  8.51it/s]
560it [01:06,  8.28it/s]  6%|███▌                                                   | 552/8674 [01:05<14:21,  9.43it/s]
568it [01:07,  7.12it/s]  6%|███▌                                                   | 560/8674 [01:06<16:19,  8.28it/s]
576it [01:08,  7.92it/s]  7%|███▌                                                   | 568/8674 [01:07<18:59,  7.12it/s]
584it [01:09,  9.08it/s]  7%|███▋                                                   | 576/8674 [01:08<17:02,  7.92it/s]
592it [01:09, 10.59it/s]  7%|███▋                                                   | 584/8674 [01:09<14:51,  9.08it/s]
600it [01:10,  9.58it/s]  7%|███▊                                                   | 592/8674 [01:09<12:43, 10.59it/s]
608it [01:11,  9.43it/s]  7%|███▊                                                   | 600/8674 [01:10<14:02,  9.58it/s]
616it [01:12,  9.09it/s]  7%|███▊                                                   | 608/8674 [01:11<14:15,  9.43it/s]
624it [01:13,  9.48it/s]  7%|███▉                                                   | 616/8674 [01:12<14:46,  9.09it/s]
632it [01:14,  9.66it/s]  7%|███▉                                                   | 624/8674 [01:13<14:09,  9.48it/s]
640it [01:14, 10.30it/s]  7%|████                                                   | 632/8674 [01:14<13:52,  9.66it/s]
648it [01:15, 10.20it/s]  7%|████                                                   | 640/8674 [01:14<12:59, 10.30it/s]
656it [01:16,  9.82it/s]  7%|████                                                   | 648/8674 [01:15<13:06, 10.20it/s]
664it [01:17,  8.94it/s]  8%|████▏                                                  | 656/8674 [01:16<13:36,  9.82it/s]
672it [01:18,  8.07it/s]  8%|████▏                                                  | 664/8674 [01:17<14:55,  8.94it/s]
680it [01:20,  7.00it/s]  8%|████▎                                                  | 672/8674 [01:18<16:31,  8.07it/s]
688it [01:21,  6.42it/s]  8%|████▎                                                  | 680/8674 [01:20<19:01,  7.00it/s]
696it [01:22,  7.25it/s]  8%|████▎                                                  | 688/8674 [01:21<20:43,  6.42it/s]
704it [01:23,  7.99it/s]  8%|████▍                                                  | 696/8674 [01:22<18:21,  7.25it/s]
712it [01:24,  8.25it/s]  8%|████▍                                                  | 704/8674 [01:23<16:37,  7.99it/s]
720it [01:25,  7.70it/s]  8%|████▌                                                  | 712/8674 [01:24<16:04,  8.25it/s]
728it [01:25,  8.79it/s]  8%|████▌                                                  | 720/8674 [01:25<17:13,  7.70it/s]
736it [01:27,  8.09it/s]  8%|████▌                                                  | 728/8674 [01:25<15:03,  8.79it/s]
744it [01:28,  7.63it/s]  8%|████▋                                                  | 736/8674 [01:27<16:21,  8.09it/s]
752it [01:29,  7.67it/s]  9%|████▋                                                  | 744/8674 [01:28<17:18,  7.63it/s]
760it [01:30,  6.85it/s]  9%|████▊                                                  | 752/8674 [01:29<17:12,  7.67it/s]
768it [01:32,  6.37it/s]  9%|████▊                                                  | 760/8674 [01:30<19:16,  6.85it/s]
776it [01:32,  7.38it/s]  9%|████▊                                                  | 768/8674 [01:32<20:41,  6.37it/s]
784it [01:33,  8.32it/s]  9%|████▉                                                  | 776/8674 [01:32<17:50,  7.38it/s]
792it [01:34,  9.57it/s]  9%|████▉                                                  | 784/8674 [01:33<15:48,  8.32it/s]
800it [01:35,  8.18it/s]  9%|█████                                                  | 792/8674 [01:34<13:43,  9.57it/s]
808it [01:36,  8.11it/s]  9%|█████                                                  | 800/8674 [01:35<16:02,  8.18it/s]
816it [01:37,  9.08it/s]  9%|█████                                                  | 808/8674 [01:36<16:09,  8.11it/s]
824it [01:38,  7.63it/s]  9%|█████▏                                                 | 816/8674 [01:37<14:25,  9.08it/s]
832it [01:39,  7.70it/s]  9%|█████▏                                                 | 824/8674 [01:38<17:08,  7.63it/s]
840it [01:40,  8.77it/s] 10%|█████▎                                                 | 832/8674 [01:39<16:58,  7.70it/s]
848it [01:40, 10.12it/s] 10%|█████▎                                                 | 840/8674 [01:40<14:53,  8.77it/s]
856it [01:41, 11.22it/s] 10%|█████▍                                                 | 848/8674 [01:40<12:53, 10.12it/s]
864it [01:41, 11.72it/s] 10%|█████▍                                                 | 856/8674 [01:41<11:37, 11.22it/s]
872it [01:42, 11.32it/s] 10%|█████▍                                                 | 864/8674 [01:41<11:06, 11.72it/s]
880it [01:43, 10.09it/s] 10%|█████▌                                                 | 872/8674 [01:42<11:29, 11.32it/s]
888it [01:44,  9.84it/s] 10%|█████▌                                                 | 880/8674 [01:43<12:52, 10.10it/s]
896it [01:45,  8.75it/s] 10%|█████▋                                                 | 888/8674 [01:44<13:11,  9.84it/s]
904it [01:46,  8.42it/s] 10%|█████▋                                                 | 896/8674 [01:45<14:48,  8.75it/s]
912it [01:47,  8.97it/s] 10%|█████▋                                                 | 904/8674 [01:46<15:22,  8.42it/s]
920it [01:47, 10.12it/s] 11%|█████▊                                                 | 912/8674 [01:47<14:25,  8.97it/s]
928it [01:48, 10.71it/s] 11%|█████▊                                                 | 920/8674 [01:47<12:46, 10.12it/s]
936it [01:49, 11.34it/s] 11%|█████▉                                                 | 928/8674 [01:48<12:03, 10.71it/s]
944it [01:50, 10.06it/s] 11%|█████▉                                                 | 936/8674 [01:49<11:22, 11.34it/s]
952it [01:50, 10.42it/s] 11%|█████▉                                                 | 944/8674 [01:50<12:48, 10.06it/s]
960it [01:51,  9.53it/s] 11%|██████                                                 | 952/8674 [01:50<12:21, 10.42it/s]
968it [01:52, 10.67it/s] 11%|██████                                                 | 960/8674 [01:51<13:29,  9.53it/s]
976it [01:53, 10.54it/s] 11%|██████▏                                                | 968/8674 [01:52<12:02, 10.67it/s]
984it [01:54,  9.14it/s] 11%|██████▏                                                | 976/8674 [01:53<12:10, 10.54it/s]
992it [01:55,  8.36it/s] 11%|██████▏                                                | 984/8674 [01:54<14:01,  9.14it/s]
1000it [01:56,  9.56it/s]11%|██████▎                                                | 992/8674 [01:55<15:18,  8.36it/s]
1008it [01:57,  7.75it/s]12%|██████▏                                               | 1000/8674 [01:56<13:22,  9.56it/s]
1016it [01:58,  6.88it/s]12%|██████▎                                               | 1008/8674 [01:57<16:29,  7.75it/s]
1024it [02:00,  6.40it/s]12%|██████▎                                               | 1016/8674 [01:58<18:33,  6.88it/s]
1032it [02:01,  6.95it/s]12%|██████▎                                               | 1024/8674 [02:00<19:55,  6.40it/s]
1040it [02:02,  7.83it/s]12%|██████▍                                               | 1032/8674 [02:01<18:18,  6.95it/s]
1048it [02:02,  9.01it/s]12%|██████▍                                               | 1040/8674 [02:02<16:14,  7.83it/s]
1056it [02:03, 10.62it/s]12%|██████▌                                               | 1048/8674 [02:02<14:06,  9.01it/s]
1064it [02:03, 10.26it/s]12%|██████▌                                               | 1056/8674 [02:03<11:57, 10.62it/s]
1072it [02:04, 10.09it/s]12%|██████▌                                               | 1064/8674 [02:03<12:21, 10.26it/s]
1080it [02:05, 10.45it/s]12%|██████▋                                               | 1072/8674 [02:04<12:33, 10.09it/s]
1088it [02:06, 10.58it/s]12%|██████▋                                               | 1080/8674 [02:05<12:06, 10.45it/s]
1096it [02:07,  9.46it/s]13%|██████▊                                               | 1088/8674 [02:06<11:56, 10.58it/s]
1104it [02:08,  8.61it/s]13%|██████▊                                               | 1096/8674 [02:07<13:20,  9.46it/s]
1112it [02:09,  8.25it/s]13%|██████▊                                               | 1104/8674 [02:08<14:38,  8.61it/s]
1120it [02:10,  8.59it/s]13%|██████▉                                               | 1112/8674 [02:09<15:16,  8.25it/s]
1128it [02:11,  8.40it/s]13%|██████▉                                               | 1120/8674 [02:10<14:39,  8.59it/s]
1136it [02:12,  8.33it/s]13%|███████                                               | 1128/8674 [02:11<14:58,  8.40it/s]
1144it [02:13,  8.78it/s]13%|███████                                               | 1136/8674 [02:12<15:04,  8.33it/s]
1152it [02:13, 10.00it/s]13%|███████                                               | 1144/8674 [02:13<14:17,  8.79it/s]
1160it [02:14,  9.14it/s]13%|███████▏                                              | 1152/8674 [02:13<12:31, 10.00it/s]
1168it [02:15,  9.18it/s]13%|███████▏                                              | 1160/8674 [02:14<13:41,  9.14it/s]
1176it [02:16,  9.99it/s]13%|███████▎                                              | 1168/8674 [02:15<13:37,  9.18it/s]
1184it [02:16, 10.70it/s]14%|███████▎                                              | 1176/8674 [02:16<12:30,  9.99it/s]
1192it [02:17, 11.43it/s]14%|███████▎                                              | 1184/8674 [02:16<11:40, 10.70it/s]
1200it [02:18, 11.62it/s]14%|███████▍                                              | 1192/8674 [02:17<10:54, 11.44it/s]
1208it [02:18, 12.27it/s]14%|███████▍                                              | 1200/8674 [02:18<10:43, 11.62it/s]
1216it [02:19, 11.18it/s]14%|███████▌                                              | 1208/8674 [02:18<10:08, 12.27it/s]
1224it [02:20,  9.46it/s]14%|███████▌                                              | 1216/8674 [02:19<11:07, 11.18it/s]
1232it [02:21,  9.00it/s]14%|███████▌                                              | 1224/8674 [02:20<13:07,  9.46it/s]
1240it [02:22,  8.77it/s]14%|███████▋                                              | 1232/8674 [02:21<13:46,  9.00it/s]
1248it [02:23,  8.41it/s]14%|███████▋                                              | 1240/8674 [02:22<14:07,  8.77it/s]
1256it [02:24,  9.47it/s]14%|███████▊                                              | 1248/8674 [02:23<14:42,  8.41it/s]
1264it [02:24, 11.39it/s]14%|███████▊                                              | 1256/8674 [02:24<13:03,  9.47it/s]
1272it [02:25, 11.51it/s]15%|███████▊                                              | 1264/8674 [02:24<10:50, 11.40it/s]
1280it [02:25, 11.26it/s]15%|███████▉                                              | 1272/8674 [02:25<10:43, 11.51it/s]
1288it [02:26, 11.07it/s]15%|███████▉                                              | 1280/8674 [02:25<10:56, 11.26it/s]
1296it [02:27,  9.85it/s]15%|████████                                              | 1288/8674 [02:26<11:07, 11.07it/s]
1304it [02:28,  8.50it/s]15%|████████                                              | 1296/8674 [02:27<12:29,  9.85it/s]
1312it [02:29,  9.18it/s]15%|████████                                              | 1304/8674 [02:28<14:27,  8.50it/s]
1320it [02:30,  9.22it/s]15%|████████▏                                             | 1312/8674 [02:29<13:22,  9.18it/s]
1328it [02:31,  8.59it/s]15%|████████▏                                             | 1320/8674 [02:30<13:17,  9.22it/s]

In [29]:
# fill in nfcorpus dense index !!!! DON'T RUN THIS I HAVE CREATED THIS ALREADY !!!!
Indexer(nfcorpus_index, d_encoder, batch_size=8).from_dicts(docs_iter(nfcorpus))

0it [00:00, ?it/s]
8it [00:01,  5.36it/s]s:   0%|                                                                | 0/3633 [00:00<?, ?it/s]
16it [00:02,  5.73it/s]:   0%|                                                        | 8/3633 [00:01<11:14,  5.38it/s]
24it [00:04,  5.64it/s]:   0%|▏                                                      | 16/3633 [00:02<10:29,  5.74it/s]
32it [00:05,  5.66it/s]:   1%|▎                                                      | 24/3633 [00:04<10:39,  5.64it/s]
40it [00:07,  5.78it/s]:   1%|▍                                                      | 32/3633 [00:05<10:36,  5.66it/s]
48it [00:08,  5.95it/s]:   1%|▌                                                      | 40/3633 [00:07<10:21,  5.78it/s]
56it [00:09,  5.74it/s]:   1%|▋                                                      | 48/3633 [00:08<10:02,  5.95it/s]
64it [00:11,  5.89it/s]:   2%|▊                                                      | 56/3633 [00:09<10:23,  5.74it/s]
72it [00:12,  5.91it/s]:   2%|▉                                                      | 64/3633 [00:11<10:05,  5.89it/s]
80it [00:13,  5.76it/s]:   2%|█                                                      | 72/3633 [00:12<10:02,  5.91it/s]
88it [00:15,  5.65it/s]:   2%|█▏                                                     | 80/3633 [00:13<10:17,  5.76it/s]
96it [00:16,  5.80it/s]:   2%|█▎                                                     | 88/3633 [00:15<10:27,  5.65it/s]
104it [00:18,  5.69it/s]   3%|█▍                                                     | 96/3633 [00:16<10:09,  5.80it/s]
112it [00:19,  5.60it/s]   3%|█▌                                                    | 104/3633 [00:18<10:19,  5.69it/s]
120it [00:21,  5.61it/s]   3%|█▋                                                    | 112/3633 [00:19<10:28,  5.60it/s]
128it [00:22,  5.74it/s]   3%|█▊                                                    | 120/3633 [00:20<10:26,  5.61it/s]
136it [00:23,  5.66it/s]   4%|█▉                                                    | 128/3633 [00:22<10:10,  5.74it/s]
144it [00:25,  5.58it/s]   4%|██                                                    | 136/3633 [00:23<10:17,  5.66it/s]
152it [00:26,  5.53it/s]   4%|██▏                                                   | 144/3633 [00:25<10:25,  5.58it/s]
160it [00:28,  5.50it/s]   4%|██▎                                                   | 152/3633 [00:26<10:29,  5.53it/s]
168it [00:29,  5.46it/s]   4%|██▍                                                   | 160/3633 [00:28<10:31,  5.50it/s]
176it [00:31,  5.63it/s]   5%|██▍                                                   | 168/3633 [00:29<10:34,  5.46it/s]
184it [00:32,  5.58it/s]   5%|██▌                                                   | 176/3633 [00:31<10:13,  5.63it/s]
192it [00:33,  5.83it/s]   5%|██▋                                                   | 184/3633 [00:32<10:18,  5.58it/s]
200it [00:34,  5.98it/s]   5%|██▊                                                   | 192/3633 [00:33<09:49,  5.83it/s]
208it [00:36,  5.82it/s]   6%|██▉                                                   | 200/3633 [00:34<09:34,  5.98it/s]
216it [00:37,  5.63it/s]   6%|███                                                   | 208/3633 [00:36<09:48,  5.82it/s]
224it [00:39,  5.72it/s]   6%|███▏                                                  | 216/3633 [00:37<10:07,  5.63it/s]
232it [00:40,  5.61it/s]   6%|███▎                                                  | 224/3633 [00:39<09:56,  5.72it/s]
240it [00:42,  5.77it/s]   6%|███▍                                                  | 232/3633 [00:40<10:06,  5.61it/s]
248it [00:43,  5.65it/s]   7%|███▌                                                  | 240/3633 [00:42<09:48,  5.77it/s]
256it [00:44,  5.86it/s]   7%|███▋                                                  | 248/3633 [00:43<09:59,  5.65it/s]
264it [00:46,  5.73it/s]   7%|███▊                                                  | 256/3633 [00:44<09:36,  5.86it/s]
272it [00:47,  5.77it/s]   7%|███▉                                                  | 264/3633 [00:46<09:48,  5.73it/s]
280it [00:49,  5.67it/s]   7%|████                                                  | 272/3633 [00:47<09:42,  5.77it/s]
288it [00:50,  5.64it/s]   8%|████▏                                                 | 280/3633 [00:49<09:51,  5.67it/s]
296it [00:51,  6.44it/s]   8%|████▎                                                 | 288/3633 [00:50<09:53,  5.64it/s]
304it [00:52,  6.34it/s]   8%|████▍                                                 | 296/3633 [00:51<08:37,  6.44it/s]
312it [00:53,  6.43it/s]   8%|████▌                                                 | 304/3633 [00:52<08:45,  6.34it/s]
320it [00:55,  6.48it/s]   9%|████▋                                                 | 312/3633 [00:53<08:36,  6.43it/s]
328it [00:56,  6.49it/s]   9%|████▊                                                 | 320/3633 [00:55<08:31,  6.48it/s]
336it [00:57,  6.28it/s]   9%|████▉                                                 | 328/3633 [00:56<08:29,  6.49it/s]
344it [00:58,  6.31it/s]   9%|████▉                                                 | 336/3633 [00:57<08:44,  6.28it/s]
352it [01:00,  6.02it/s]   9%|█████                                                 | 344/3633 [00:58<08:40,  6.31it/s]
360it [01:01,  6.14it/s]  10%|█████▏                                                | 352/3633 [01:00<09:05,  6.02it/s]
368it [01:03,  5.90it/s]  10%|█████▎                                                | 360/3633 [01:01<08:53,  6.14it/s]
376it [01:04,  5.79it/s]  10%|█████▍                                                | 368/3633 [01:03<09:13,  5.90it/s]
384it [01:05,  6.09it/s]  10%|█████▌                                                | 376/3633 [01:04<09:22,  5.79it/s]
392it [01:07,  6.05it/s]  11%|█████▋                                                | 384/3633 [01:05<08:53,  6.09it/s]
400it [01:08,  6.24it/s]  11%|█████▊                                                | 392/3633 [01:07<08:55,  6.05it/s]
408it [01:09,  6.13it/s]  11%|█████▉                                                | 400/3633 [01:08<08:37,  6.24it/s]
416it [01:10,  6.56it/s]  11%|██████                                                | 408/3633 [01:09<08:45,  6.13it/s]
424it [01:12,  6.17it/s]  11%|██████▏                                               | 416/3633 [01:10<08:10,  6.56it/s]
432it [01:13,  6.50it/s]  12%|██████▎                                               | 424/3633 [01:12<08:40,  6.17it/s]
440it [01:14,  6.55it/s]  12%|██████▍                                               | 432/3633 [01:13<08:12,  6.50it/s]
448it [01:15,  6.17it/s]  12%|██████▌                                               | 440/3633 [01:14<08:07,  6.55it/s]
456it [01:17,  6.09it/s]  12%|██████▋                                               | 448/3633 [01:15<08:36,  6.17it/s]
464it [01:18,  5.88it/s]  13%|██████▊                                               | 456/3633 [01:17<08:41,  6.09it/s]
472it [01:20,  5.86it/s]  13%|██████▉                                               | 464/3633 [01:18<08:58,  5.88it/s]
480it [01:21,  5.72it/s]  13%|███████                                               | 472/3633 [01:20<08:59,  5.86it/s]
488it [01:22,  6.03it/s]  13%|███████▏                                              | 480/3633 [01:21<09:10,  5.72it/s]
496it [01:23,  6.31it/s]  13%|███████▎                                              | 488/3633 [01:22<08:41,  6.03it/s]
504it [01:25,  6.02it/s]  14%|███████▎                                              | 496/3633 [01:23<08:17,  6.31it/s]
512it [01:26,  5.82it/s]  14%|███████▍                                              | 504/3633 [01:25<08:39,  6.02it/s]
520it [01:28,  5.71it/s]  14%|███████▌                                              | 512/3633 [01:26<08:56,  5.82it/s]
528it [01:29,  5.63it/s]  14%|███████▋                                              | 520/3633 [01:28<09:05,  5.71it/s]
536it [01:30,  6.04it/s]  15%|███████▊                                              | 528/3633 [01:29<09:11,  5.63it/s]
544it [01:32,  6.11it/s]  15%|███████▉                                              | 536/3633 [01:30<08:32,  6.04it/s]
552it [01:33,  6.50it/s]  15%|████████                                              | 544/3633 [01:32<08:25,  6.11it/s]
560it [01:34,  6.70it/s]  15%|████████▏                                             | 552/3633 [01:33<07:54,  6.50it/s]
568it [01:35,  6.26it/s]  15%|████████▎                                             | 560/3633 [01:34<07:38,  6.70it/s]
576it [01:37,  6.00it/s]  16%|████████▍                                             | 568/3633 [01:35<08:09,  6.26it/s]
584it [01:38,  5.85it/s]  16%|████████▌                                             | 576/3633 [01:37<08:29,  6.00it/s]
592it [01:40,  5.74it/s]  16%|████████▋                                             | 584/3633 [01:38<08:40,  5.85it/s]
600it [01:41,  5.79it/s]  16%|████████▊                                             | 592/3633 [01:40<08:50,  5.74it/s]
608it [01:42,  5.87it/s]  17%|████████▉                                             | 600/3633 [01:41<08:44,  5.79it/s]
616it [01:43,  6.17it/s]  17%|█████████                                             | 608/3633 [01:42<08:35,  5.87it/s]
624it [01:45,  5.92it/s]  17%|█████████▏                                            | 616/3633 [01:43<08:09,  6.17it/s]
632it [01:46,  5.75it/s]  17%|█████████▎                                            | 624/3633 [01:45<08:28,  5.92it/s]
640it [01:48,  6.01it/s]  17%|█████████▍                                            | 632/3633 [01:46<08:41,  5.75it/s]
648it [01:49,  6.34it/s]  18%|█████████▌                                            | 640/3633 [01:48<08:17,  6.01it/s]
656it [01:50,  6.07it/s]  18%|█████████▋                                            | 648/3633 [01:49<07:50,  6.34it/s]
664it [01:51,  6.35it/s]  18%|█████████▊                                            | 656/3633 [01:50<08:10,  6.07it/s]
672it [01:53,  5.97it/s]  18%|█████████▊                                            | 664/3633 [01:51<07:47,  6.35it/s]
680it [01:54,  5.80it/s]  18%|█████████▉                                            | 672/3633 [01:53<08:16,  5.97it/s]
688it [01:55,  6.07it/s]  19%|██████████                                            | 680/3633 [01:54<08:29,  5.80it/s]
696it [01:57,  6.27it/s]  19%|██████████▏                                           | 688/3633 [01:55<08:05,  6.07it/s]
704it [01:58,  6.49it/s]  19%|██████████▎                                           | 696/3633 [01:57<07:48,  6.27it/s]
712it [01:59,  6.15it/s]  19%|██████████▍                                           | 704/3633 [01:58<07:31,  6.49it/s]
720it [02:00,  6.56it/s]  20%|██████████▌                                           | 712/3633 [01:59<07:55,  6.15it/s]
728it [02:02,  6.18it/s]  20%|██████████▋                                           | 720/3633 [02:00<07:24,  6.56it/s]
736it [02:03,  6.35it/s]  20%|██████████▊                                           | 728/3633 [02:02<07:49,  6.18it/s]
744it [02:04,  6.05it/s]  20%|██████████▉                                           | 736/3633 [02:03<07:36,  6.35it/s]
752it [02:06,  5.92it/s]  20%|███████████                                           | 744/3633 [02:04<07:57,  6.05it/s]
760it [02:07,  5.75it/s]  21%|███████████▏                                          | 752/3633 [02:06<08:06,  5.92it/s]
768it [02:09,  5.64it/s]  21%|███████████▎                                          | 760/3633 [02:07<08:19,  5.75it/s]
776it [02:10,  6.07it/s]  21%|███████████▍                                          | 768/3633 [02:09<08:27,  5.64it/s]
784it [02:11,  6.09it/s]  21%|███████████▌                                          | 776/3633 [02:10<07:50,  6.07it/s]
792it [02:12,  6.11it/s]  22%|███████████▋                                          | 784/3633 [02:11<07:47,  6.09it/s]
800it [02:14,  5.88it/s]  22%|███████████▊                                          | 792/3633 [02:12<07:44,  6.11it/s]
808it [02:15,  5.61it/s]  22%|███████████▉                                          | 800/3633 [02:14<08:02,  5.88it/s]
816it [02:17,  5.57it/s]  22%|████████████                                          | 808/3633 [02:15<08:23,  5.61it/s]
824it [02:18,  6.41it/s]  22%|████████████▏                                         | 816/3633 [02:17<08:25,  5.58it/s]
832it [02:19,  6.30it/s]  23%|████████████▏                                         | 824/3633 [02:18<07:18,  6.41it/s]
840it [02:20,  6.27it/s]  23%|████████████▎                                         | 832/3633 [02:19<07:24,  6.30it/s]
848it [02:22,  5.98it/s]  23%|████████████▍                                         | 840/3633 [02:20<07:25,  6.27it/s]
856it [02:23,  6.29it/s]  23%|████████████▌                                         | 848/3633 [02:22<07:45,  5.98it/s]
864it [02:24,  6.32it/s]  24%|████████████▋                                         | 856/3633 [02:23<07:21,  6.29it/s]
872it [02:26,  6.04it/s]  24%|████████████▊                                         | 864/3633 [02:24<07:17,  6.32it/s]
880it [02:27,  6.04it/s]  24%|████████████▉                                         | 872/3633 [02:26<07:37,  6.04it/s]
888it [02:28,  5.82it/s]  24%|█████████████                                         | 880/3633 [02:27<07:35,  6.04it/s]
896it [02:30,  5.90it/s]  24%|█████████████▏                                        | 888/3633 [02:28<07:52,  5.82it/s]
904it [02:31,  5.75it/s]  25%|█████████████▎                                        | 896/3633 [02:30<07:44,  5.90it/s]
912it [02:33,  5.64it/s]  25%|█████████████▍                                        | 904/3633 [02:31<07:54,  5.75it/s]
920it [02:34,  5.80it/s]  25%|█████████████▌                                        | 912/3633 [02:33<08:02,  5.64it/s]
928it [02:35,  5.68it/s]  25%|█████████████▋                                        | 920/3633 [02:34<07:47,  5.80it/s]
936it [02:37,  5.60it/s]  26%|█████████████▊                                        | 928/3633 [02:35<07:55,  5.68it/s]
944it [02:38,  5.55it/s]  26%|█████████████▉                                        | 936/3633 [02:37<08:01,  5.60it/s]
952it [02:40,  5.53it/s]  26%|██████████████                                        | 944/3633 [02:38<08:04,  5.55it/s]
960it [02:41,  5.50it/s]  26%|██████████████▏                                       | 952/3633 [02:40<08:04,  5.53it/s]
968it [02:43,  5.48it/s]  26%|██████████████▎                                       | 960/3633 [02:41<08:06,  5.50it/s]
976it [02:44,  5.41it/s]  27%|██████████████▍                                       | 968/3633 [02:43<08:06,  5.48it/s]
984it [02:46,  5.79it/s]  27%|██████████████▌                                       | 976/3633 [02:44<08:11,  5.41it/s]
992it [02:47,  5.66it/s]  27%|██████████████▋                                       | 984/3633 [02:46<07:37,  5.79it/s]
1000it [02:49,  5.56it/s] 27%|██████████████▋                                       | 992/3633 [02:47<07:46,  5.66it/s]
1008it [02:50,  5.53it/s] 28%|██████████████▌                                      | 1000/3633 [02:49<07:53,  5.56it/s]
1016it [02:51,  5.83it/s] 28%|██████████████▋                                      | 1008/3633 [02:50<07:54,  5.53it/s]
1024it [02:53,  5.84it/s] 28%|██████████████▊                                      | 1016/3633 [02:51<07:29,  5.83it/s]
1032it [02:54,  6.04it/s] 28%|██████████████▉                                      | 1024/3633 [02:53<07:26,  5.84it/s]
1040it [02:55,  5.80it/s] 28%|███████████████                                      | 1032/3633 [02:54<07:10,  6.04it/s]
1048it [02:57,  5.68it/s] 29%|███████████████▏                                     | 1040/3633 [02:55<07:27,  5.80it/s]
1056it [02:58,  5.58it/s] 29%|███████████████▎                                     | 1048/3633 [02:57<07:35,  5.68it/s]
1064it [03:00,  5.66it/s] 29%|███████████████▍                                     | 1056/3633 [02:58<07:41,  5.58it/s]
1072it [03:01,  5.87it/s] 29%|███████████████▌                                     | 1064/3633 [03:00<07:33,  5.66it/s]
1080it [03:02,  5.71it/s] 30%|███████████████▋                                     | 1072/3633 [03:01<07:16,  5.87it/s]
1088it [03:04,  5.61it/s] 30%|███████████████▊                                     | 1080/3633 [03:02<07:27,  5.71it/s]
1096it [03:05,  6.13it/s] 30%|███████████████▊                                     | 1088/3633 [03:04<07:33,  5.61it/s]
1104it [03:06,  6.09it/s] 30%|███████████████▉                                     | 1096/3633 [03:05<06:54,  6.13it/s]
1112it [03:07,  6.58it/s] 30%|████████████████                                     | 1104/3633 [03:06<06:55,  6.09it/s]
1120it [03:09,  6.15it/s] 31%|████████████████▏                                    | 1112/3633 [03:07<06:22,  6.58it/s]
1128it [03:10,  6.49it/s] 31%|████████████████▎                                    | 1120/3633 [03:09<06:48,  6.15it/s]
1136it [03:11,  6.17it/s] 31%|████████████████▍                                    | 1128/3633 [03:10<06:25,  6.49it/s]
1144it [03:13,  5.92it/s] 31%|████████████████▌                                    | 1136/3633 [03:11<06:44,  6.17it/s]
1152it [03:14,  6.04it/s] 31%|████████████████▋                                    | 1144/3633 [03:13<07:00,  5.92it/s]
1160it [03:15,  5.86it/s] 32%|████████████████▊                                    | 1152/3633 [03:14<06:50,  6.04it/s]
1168it [03:17,  5.79it/s] 32%|████████████████▉                                    | 1160/3633 [03:15<07:02,  5.86it/s]
1176it [03:18,  5.84it/s] 32%|█████████████████                                    | 1168/3633 [03:17<07:05,  5.79it/s]
1184it [03:20,  5.71it/s] 32%|█████████████████▏                                   | 1176/3633 [03:18<07:00,  5.84it/s]
1192it [03:21,  5.62it/s] 33%|█████████████████▎                                   | 1184/3633 [03:20<07:09,  5.71it/s]
1200it [03:23,  5.55it/s] 33%|█████████████████▍                                   | 1192/3633 [03:21<07:14,  5.62it/s]
1208it [03:24,  5.83it/s] 33%|█████████████████▌                                   | 1200/3633 [03:23<07:18,  5.55it/s]
1216it [03:25,  5.71it/s] 33%|█████████████████▌                                   | 1208/3633 [03:24<06:55,  5.83it/s]
1224it [03:27,  5.77it/s] 33%|█████████████████▋                                   | 1216/3633 [03:25<07:03,  5.71it/s]
1232it [03:28,  5.68it/s] 34%|█████████████████▊                                   | 1224/3633 [03:27<06:57,  5.77it/s]
1240it [03:30,  5.60it/s] 34%|█████████████████▉                                   | 1232/3633 [03:28<07:02,  5.68it/s]
1248it [03:31,  5.69it/s] 34%|██████████████████                                   | 1240/3633 [03:30<07:07,  5.60it/s]
1256it [03:32,  5.87it/s] 34%|██████████████████▏                                  | 1248/3633 [03:31<06:59,  5.69it/s]
1264it [03:34,  5.73it/s] 35%|██████████████████▎                                  | 1256/3633 [03:32<06:45,  5.87it/s]
1272it [03:35,  5.78it/s] 35%|██████████████████▍                                  | 1264/3633 [03:34<06:53,  5.73it/s]
1280it [03:36,  5.68it/s] 35%|██████████████████▌                                  | 1272/3633 [03:35<06:48,  5.78it/s]
1288it [03:38,  5.60it/s] 35%|██████████████████▋                                  | 1280/3633 [03:36<06:54,  5.68it/s]
1296it [03:39,  6.56it/s] 35%|██████████████████▊                                  | 1288/3633 [03:38<06:58,  5.60it/s]
1304it [03:40,  6.64it/s] 36%|██████████████████▉                                  | 1296/3633 [03:39<05:56,  6.56it/s]
1312it [03:41,  6.65it/s] 36%|███████████████████                                  | 1304/3633 [03:40<05:50,  6.64it/s]
1320it [03:42,  6.50it/s] 36%|███████████████████▏                                 | 1312/3633 [03:41<05:48,  6.65it/s]
1328it [03:44,  6.45it/s] 36%|███████████████████▎                                 | 1320/3633 [03:42<05:55,  6.50it/s]

In [30]:
# Load scifact index into memory
def LoadFromDisk(data_name):
    index_name = "ffindex_" + data_name + "_tasb.h5"
    index = OnDiskIndex.load(
    Path.cwd() / "ir_experiments" / index_name,
    query_encoder=q_encoder,
    mode=Mode.MAXP,
    )
    return index

In [31]:
# load indexes into memory
scifact_index = LoadFromDisk("scifact")
scifact_index = scifact_index.to_memory()

fiqa_index = LoadFromDisk("fiqa")
fiqa_index = fiqa_index.to_memory()

arguana_index =LoadFromDisk("arguana")
arguana_index = arguana_index.to_memory()

nfcorpus_index = LoadFromDisk("nfcorpus")
nfcorpus_index = nfcorpus_index.to_memory()

100%|█████████████████████████████████████████████████████████████████████████| 5183/5183 [00:00<00:00, 1253406.23it/s]
100%|████████████████████████████████████████████████████████████████████████| 57638/57638 [00:00<00:00, 277005.83it/s]
100%|█████████████████████████████████████████████████████████████████████████| 8674/8674 [00:00<00:00, 1422314.90it/s]
100%|█████████████████████████████████████████████████████████████████████████| 3633/3633 [00:00<00:00, 1746064.68it/s]

### Reranking BM25 results
Now that we have dealt with all the dense indexes we can use BM25 to retrieve some documents and then use the reranking pipeline

In [33]:
def twoStageCandidateDepthExperiment(dense_index,test_dataset,dataset_name,bm25,candidate_depths,alpha_value=0.5):
    
    ff_score = FFScore(dense_index)
    ff_int = FFInterpolate(alpha=alpha_value) # we used a fixed alpha here maybe this needs to change
    pipelines = [bm25]
    names = ["BM25"]
    
    for k in candidate_depths:
        # generate the two stage pipe
        # bm25 retrieves top-k then tasb rescores them then we use interpolation to combine scores
        pipe = (bm25%k) >> ff_score >> ff_int
        pipelines.append(pipe)
        names.append(f"BM25 >> TAS-B (k={k})")
    print(f"Results for {dataset_name} ")
    results = pt.Experiment(
        pipelines,
        test_dataset.get_topics("text"),
        test_dataset.get_qrels(),
        eval_metrics=[RR @ 10, nDCG @ 10, MAP @ 100],
        names=names,
    )
    print(results)

# this list will be used to find the best k for each of the datasets
candidate_depths = [10,50,100,200,300,400,500,800,1000]

In [24]:
# run experiment on any dataset I want
twoStageCandidateDepthExperiment(scifact_index, testset_scifact, "SciFact", bm25_scifact,candidate_depths)

Results for SciFact
                     name     RR@10   nDCG@10    AP@100
0                    BM25  0.632427  0.672167  0.626749
1    BM25 >> TAS-B (k=10)  0.650517  0.685043  0.637451
2    BM25 >> TAS-B (k=50)  0.651521  0.689003  0.643959
3   BM25 >> TAS-B (k=100)  0.650354  0.687411  0.644392
4   BM25 >> TAS-B (k=200)  0.650831  0.688523  0.644888
5   BM25 >> TAS-B (k=300)  0.650831  0.688523  0.644836
6   BM25 >> TAS-B (k=400)  0.650831  0.688523  0.644933
7   BM25 >> TAS-B (k=500)  0.650831  0.688523  0.645123
8   BM25 >> TAS-B (k=800)  0.650831  0.688523  0.645123
9  BM25 >> TAS-B (k=1000)  0.650831  0.688523  0.645123

### Interpretation and best k - SciFact
A key result I can see from the neural reranking while adjusting the candidate depth for scifact is that performance saturates somewhere around 100-200 candidate depth (nDCG@10 and MAP@100 both go flat around 200). Increasing candidate depth beyond this depth doesn't yield any improvements. To balance efficiency and effectiveness , the **best k for SciFact is k=100**

In [21]:
twoStageCandidateDepthExperiment(fiqa_index, testset_fiqa, "FIQA", bm25_fiqa,candidate_depths)

Results for fiqa
                     name     RR@10   nDCG@10    AP@100
0                    BM25  0.310271  0.252589  0.208640
1    BM25 >> TAS-B (k=10)  0.349528  0.274255  0.219525
2    BM25 >> TAS-B (k=50)  0.367266  0.302927  0.245519
3   BM25 >> TAS-B (k=100)  0.368838  0.304480  0.250095
4   BM25 >> TAS-B (k=200)  0.369985  0.306637  0.252817
5   BM25 >> TAS-B (k=300)  0.369933  0.306817  0.253445
6   BM25 >> TAS-B (k=400)  0.370282  0.307112  0.253751
7   BM25 >> TAS-B (k=500)  0.371054  0.308301  0.254914
8   BM25 >> TAS-B (k=800)  0.371311  0.308638  0.255154
9  BM25 >> TAS-B (k=1000)  0.370925  0.308329  0.254810

### Interpretation and best k - FIQA
Although the strictly best k is k = 800 (nDCG@10 and MAP@100 highest values), going from k=1 to k=200 the gains are significant, however going from 200-1000 the gain is almost flat. Especially if I inspect the range from 500 to 1000 there is marginal gain. So taking into consideration the Efficiency vs Effectiveness tradeoff we believe that **k=200 , for FIQA** is the best for near-optimal performance

In [19]:
# !!!!!!!!!!!!!!!!!!!!!!DON'T RUN THIS AGAIN IT TAKES FAR TOO LONG!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
twoStageCandidateDepthExperiment(arguana_index,testset_arguana,"arguana",bm25_arguana,candidate_depths)

Results for arguana
                     name     RR@10   nDCG@10    AP@100
0                    BM25  0.225617  0.342442  0.236988
1    BM25 >> TAS-B (k=10)  0.232441  0.347960  0.232026
2    BM25 >> TAS-B (k=50)  0.235005  0.353437  0.245761
3   BM25 >> TAS-B (k=100)  0.235023  0.353456  0.246529
4   BM25 >> TAS-B (k=200)  0.235125  0.353693  0.246860
5   BM25 >> TAS-B (k=300)  0.235125  0.353693  0.246844
6   BM25 >> TAS-B (k=400)  0.235125  0.353693  0.246848
7   BM25 >> TAS-B (k=500)  0.235125  0.353693  0.246857
8   BM25 >> TAS-B (k=800)  0.235125  0.353693  0.246864
9  BM25 >> TAS-B (k=1000)  0.235125  0.353693  0.246873

### Interpretation and best k - ArguAna
The results here are clear, after k=200 we see marginal if any improvement in nDCG@10 and MAP@100. It is worth noting that going deep in candidate depth here is very expensive and takes a lot of time due to the structure of the dataset. Taking this into consideration and the fact that performance saturates between k=100 and k=200 , we believe that the **best k for ArguAna is k=100**

In [34]:
# !!!!!!!!!!!!!!!!!!!!!!DON'T RUN THIS AGAIN IT TAKES FAR TOO LONG!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
twoStageCandidateDepthExperiment(nfcorpus_index,testset_nfcorpus,"NFCorpus",bm25_nfcorpus,candidate_depths)

Results for NFCorpus
                     name     RR@10   nDCG@10    AP@100
0                    BM25  0.534378  0.322219  0.143582
1    BM25 >> TAS-B (k=10)  0.535859  0.323960  0.120096
2    BM25 >> TAS-B (k=50)  0.542887  0.337396  0.145438
3   BM25 >> TAS-B (k=100)  0.543497  0.339343  0.150670
4   BM25 >> TAS-B (k=200)  0.543110  0.339590  0.152021
5   BM25 >> TAS-B (k=300)  0.543110  0.339796  0.151994
6   BM25 >> TAS-B (k=400)  0.543110  0.339539  0.152180
7   BM25 >> TAS-B (k=500)  0.543110  0.339539  0.152182
8   BM25 >> TAS-B (k=800)  0.543110  0.339539  0.152212
9  BM25 >> TAS-B (k=1000)  0.543110  0.339539  0.152273

### Interpretation and best k - NFCorpus
The results here are clear, performance improves substantially up to around k=100 and then it saturates with marginal improvement until k=200 (we see marginal if any improvement in nDCG@10 and MAP@100). Taking into consideration effectiveness vs efficiency, we believe that the **best k for NFCorpus is k=100** (approximately, as it might be near optimal)

## Phase 3 - Test robustness of alpha parameter

Tune alpha on one dataset, and apply it to all the others


Have a list for "best alpha" per dataset. Try this alpha on all other datasets. We used a fixed candidade depth in all the datasets. After the tests in phase 2, in order to balance efficiency with effectiveness we are going to use **fixed k value = 100** , which seems to be near optimal for all the datasets tested.

In [35]:
fixed_k_value = 100

In [54]:
# we pass in the dataset to find the best alpha for the specific dataset (e.g SciFact) then we use this alpha
def findBestAlpha(bm25, ff_score,dataset, candidate_depth=100):
    alphas = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
    ff_int = FFInterpolate(alpha=0.5)
    gs = pt.GridSearch(
    (bm25 % candidate_depth) >> ff_score >> ff_int,
    {ff_int: {"alpha": alphas}},
    dataset.get_topics("text"),
    dataset.get_qrels(),
    "map",
    verbose=True,
    )
    best_alpha = ff_int.get_parameter("alpha")
    print("Best alpha is:",best_alpha)
    return best_alpha

# def evaluateBestAlpha(bm25,best_ff_pipe,testset,tested_name):

#     results = pt.Experiment(
#         [bm25, best_ff_pipe],
#         testset.get_topics("text"),
#         testset.get_qrels(),
#         eval_metrics=[RR @ 10, nDCG @ 10, MAP @ 100],
#         names=["BM25", "BM25 >> FF (tuned α)"],
#         )
#     print(results)

In [55]:
# since I want to test how well the alpha parameter generalizes I can find it upon performing the process on the dataset
# of each domain and then testing this alpha on the other three datasets.
dataset_names = ["FIQA","SciFact","ArguAna","NFCorpus"]
all_datasets = [testset_fiqa, testset_scifact, testset_arguana, testset_nfcorpus]
all_bm25 = [bm25_fiqa,bm25_scifact,bm25_arguana,bm25_nfcorpus]
all_dense_indexes = [fiqa_index,scifact_index,arguana_index,nfcorpus_index]
best_alpha_per_pipeline = []

for i in range(len(all_datasets)): # we find the optimal on each of the datasets and test it on the other (different domain) datasets
    best_alpha_per_pipeline.append(findBestAlpha(all_bm25[i],FFScore(all_dense_indexes[i]),all_datasets[i],fixed_k_value))

GridScan: 100%|██████████████████████████████████████████████████████████████████████████| 9/9 [02:43<00:00, 18.18s/it]

Best map is 0.260343
Best setting is ['<fast_forward.util.pyterrier.FFInterpolate object at 0x0000021D50FC7050> alpha=0.2']
Best alpha is: 0.2

GridScan: 100%|██████████████████████████████████████████████████████████████████████████| 9/9 [01:23<00:00,  9.33s/it]

Best map is 0.652447
Best setting is ['<fast_forward.util.pyterrier.FFInterpolate object at 0x0000021D65331860> alpha=0.3']
Best alpha is: 0.3

GridScan: 100%|█████████████████████████████████████████████████████████████████████████| 9/9 [42:23<00:00, 282.58s/it]

Best map is 0.246529
Best setting is ['<fast_forward.util.pyterrier.FFInterpolate object at 0x0000021D65331860> alpha=0.5']
Best alpha is: 0.5

GridScan: 100%|██████████████████████████████████████████████████████████████████████████| 9/9 [00:49<00:00,  5.49s/it]

Best map is 0.152672
Best setting is ['<fast_forward.util.pyterrier.FFInterpolate object at 0x0000021D652F45F0> alpha=0.4']
Best alpha is: 0.4

In [ ]:
# Grid search takes a long time so just in case something goes wrong and we lose progress:
substitute_grid_search_values = [0.2,0.3,0.5,0.4]

In [58]:
# Now best_alpha_per_pipeline can be used on each of the other datasets

for i in range(len(best_alpha_per_pipeline)):
    current_optimal = best_alpha_per_pipeline[i]
    for j in range(len(best_alpha_per_pipeline)):
        if i == j:
            continue
    # else call function that tests the result with specific alpha.
        print(f"Testing optimal alpha of {dataset_names[i]} with dataset: {dataset_names[j]}\n")
        twoStageCandidateDepthExperiment(all_dense_indexes[j],all_datasets[j],dataset_names[j],all_bm25[j],[fixed_k_value],current_optimal)
 # this also takes quite some time to get results, due to ArguAna

Testing optimal alpha of FIQA with dataset: SciFact

Results for SciFact
                    name     RR@10   nDCG@10    AP@100
0                   BM25  0.632427  0.672167  0.626749
1  BM25 >> TAS-B (k=100)  0.645960  0.678132  0.640733
Testing optimal alpha of FIQA with dataset: ArguAna

Results for ArguAna
                    name     RR@10   nDCG@10    AP@100
0                   BM25  0.225617  0.342442  0.236988
1  BM25 >> TAS-B (k=100)  0.228982  0.346624  0.240296
Testing optimal alpha of FIQA with dataset: NFCorpus

Results for NFCorpus
                    name     RR@10   nDCG@10    AP@100
0                   BM25  0.534378  0.322219  0.143582
1  BM25 >> TAS-B (k=100)  0.550047  0.334810  0.151108
Testing optimal alpha of SciFact with dataset: FIQA

Results for FIQA
                    name     RR@10   nDCG@10    AP@100
0                   BM25  0.310271  0.252589  0.208640
1  BM25 >> TAS-B (k=100)  0.376556  0.313697  0.258812
Testing optimal alpha of SciFact with dataset: ArguAna

Results for ArguAna
                    name     RR@10   nDCG@10    AP@100
0                   BM25  0.225617  0.342442  0.236988
1  BM25 >> TAS-B (k=100)  0.233651  0.352439  0.244986
Testing optimal alpha of SciFact with dataset: NFCorpus

Results for NFCorpus
                    name     RR@10   nDCG@10    AP@100
0                   BM25  0.534378  0.322219  0.143582
1  BM25 >> TAS-B (k=100)  0.552750  0.338451  0.152496
Testing optimal alpha of ArguAna with dataset: FIQA

Results for FIQA
                    name     RR@10   nDCG@10    AP@100
0                   BM25  0.310271  0.252589  0.208640
1  BM25 >> TAS-B (k=100)  0.368838  0.304480  0.250095
Testing optimal alpha of ArguAna with dataset: SciFact

Results for SciFact
                    name     RR@10   nDCG@10    AP@100
0                   BM25  0.632427  0.672167  0.626749
1  BM25 >> TAS-B (k=100)  0.650354  0.687411  0.644392
Testing optimal alpha of ArguAna with dataset: NFCorpus

Results for NFCorpus
                    name     RR@10   nDCG@10    AP@100
0                   BM25  0.534378  0.322219  0.143582
1  BM25 >> TAS-B (k=100)  0.543497  0.339343  0.150670
Testing optimal alpha of NFCorpus with dataset: FIQA

Results for FIQA
                    name     RR@10   nDCG@10    AP@100
0                   BM25  0.310271  0.252589  0.208640
1  BM25 >> TAS-B (k=100)  0.374367  0.309224  0.254826
Testing optimal alpha of NFCorpus with dataset: SciFact

Results for SciFact
                    name     RR@10   nDCG@10    AP@100
0                   BM25  0.632427  0.672167  0.626749
1  BM25 >> TAS-B (k=100)  0.652213  0.689672  0.646667
Testing optimal alpha of NFCorpus with dataset: ArguAna

Results for ArguAna
                    name     RR@10   nDCG@10    AP@100
0                   BM25  0.225617  0.342442  0.236988
1  BM25 >> TAS-B (k=100)  0.234439  0.352312  0.246490

### Note 
maybe to properly test if it generalizes well we have to also check how the optimal alphas work on the same dataset or something, at least for the ones that have the test,train,dev split